### ISSUE TITLE
an error when I run the TSN experiments on Charades

### ISSUE THREAD

**Issue by icyzhang0923** [gsig/PyVideoResearch#25]
When I run the TSN experiments on Charades, I meet a problem:

Traceback (most recent call last):
  File "/media/icyzhang/SSD/PyVideoResearch-master/baseline_exp/temporal_segment_networks_charades.py", line 54, in <module>
    main()
  File "/media/icyzhang/SSD/PyVideoResearch-master/main.py", line 106, in main
    scores.update(trainer.train(train_loader, model, criterion, optimizer, epoch, metrics, args))
  File "/media/icyzhang/SSD/PyVideoResearch-master/train.py", line 61, in train
    output = model(input, meta)
  File "/home/icyzhang/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/icyzhang/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 143, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/icyzhang/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 153, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/icyzhang/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
    raise output
  File "/home/icyzhang/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 59, in _worker
    output = module(*input, **kwargs)
TypeError: TSNBase2 object argument after ** must be a mapping, not tuple

**Comment by gsig** [comment]
The error is complaining that a passed keyword argument to TSN base is
somehow a tuple, not a dict. I have not tested the TSN baseline recently,
so there is likely some code drift, either in this codebase, or relative to
PyTorch etc. You could pull the repo at the got hash given in the baseline
to figure out if it's this codebase or not. If it's a drift relative to
PyTorch my guess is that it might have to do with our extension of the
collate function to support arbitrary meta inputs:
https://github.com/gsig/PyVideoResearch/blob/master/datasets/get.py
otherwise it's likely some function signature somewhere.

If you do figure it out, consider submitting a pull request to help others.

Best,
Gunnar
